name: colombia_holidays
description: Flutter package to know the holidays in Colombia, you can get all the holidays per year or determine if a date is a holiday.
version: 2.1.5
homepage: https://smart-dev.com.co
repository: https://github.com/reyesmfabian/colombia_holidays_package

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/colombia_holidays/assets/holidays.json
